language: android
jdk:
    - oraclejdk7
android:
    components:
        - tools
        - build-tools-25.0.0
        - platform-tools
        - android-19
script:
   - cd app
   - chmod +x ./gradlew
   - ./gradlew build connectedCheck
